-- Seed system finding templates (vulnerability knowledge base)
INSERT INTO "finding_templates" ("title", "category", "overview", "overview_format", "impact", "impact_format", "recommendation", "recommendation_format", "severity", "cvss_score", "cvss_vector", "is_system")
VALUES
(
  'SQL Injection',
  'web',
  E'The application is vulnerable to SQL injection, a class of vulnerability that allows an attacker to manipulate backend database queries by injecting arbitrary SQL syntax into application inputs. By crafting malicious input, an attacker can bypass authentication, extract sensitive data, modify or delete records, and in some cases execute operating system commands on the database server.\n\nDuring testing, it was confirmed that user-supplied input is concatenated directly into SQL queries without proper sanitization or parameterization. This was demonstrated by injecting SQL syntax into [parameter/endpoint] and observing altered query behavior.',
  'markdown',
  E'Successful exploitation of this vulnerability could allow an attacker to:\n\n- **Read** all data in the database, including user credentials, personal information, and application secrets\n- **Modify** existing records, including escalating privileges or altering business-critical data\n- **Delete** data, causing loss of availability and potential compliance violations\n- **Execute** operating system commands on the database server (depending on database configuration and privileges)\n- **Pivot** to internal systems accessible from the database server',
  'markdown',
  E'1. **Use parameterized queries (prepared statements)** for all database interactions. Never concatenate user input directly into SQL strings\n2. **Implement input validation** using an allow-list approach for expected data types, lengths, and formats\n3. **Apply the principle of least privilege** to database accounts used by the application — restrict to only the tables and operations required\n4. **Deploy a Web Application Firewall (WAF)** as an additional defense-in-depth layer\n5. **Conduct a code review** of all database interaction points to identify and remediate additional injection vectors',
  'markdown',
  'critical',
  9.8,
  'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
  true
),
(
  'Cross-Site Scripting (XSS) — Reflected',
  'web',
  E'A reflected cross-site scripting (XSS) vulnerability was identified in the application. User-supplied input is reflected back in the HTTP response without adequate encoding or sanitization, allowing an attacker to inject and execute arbitrary JavaScript in the context of a victim''s browser session.\n\nThis type of XSS requires the victim to click a specially crafted link. The injected script executes with the full privileges of the user''s session, enabling session hijacking, credential theft, and arbitrary actions on behalf of the user.',
  'markdown',
  E'An attacker exploiting this vulnerability could:\n\n- **Hijack user sessions** by stealing session cookies or tokens\n- **Perform actions** on behalf of the victim user (account takeover)\n- **Redirect users** to malicious websites for credential phishing\n- **Deface** the application content as seen by the victim\n- **Deliver malware** or exploit browser vulnerabilities',
  'markdown',
  E'1. **Encode all output** — apply context-appropriate encoding (HTML entity, JavaScript, URL, CSS) to all user-controlled data before rendering in the response\n2. **Implement Content Security Policy (CSP)** headers to restrict script execution sources\n3. **Use modern framework auto-escaping** features (React JSX, Angular templates) and avoid `dangerouslySetInnerHTML` or equivalent\n4. **Validate input** server-side using strict allow-lists for expected data formats\n5. **Set HttpOnly and Secure flags** on session cookies to limit the impact of successful XSS',
  'markdown',
  'medium',
  6.1,
  'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N',
  true
),
(
  'Cross-Site Scripting (XSS) — Stored',
  'web',
  E'A stored (persistent) cross-site scripting vulnerability was identified. Malicious JavaScript injected through user input is stored in the application''s database and rendered to other users without sanitization. Unlike reflected XSS, this variant does not require the victim to click a crafted link — the payload executes automatically when any user views the affected page.\n\nThis makes stored XSS significantly more dangerous as it can affect all users who visit the page, including administrators.',
  'markdown',
  E'Exploitation could allow an attacker to:\n\n- **Mass session hijacking** across all users who view the affected content\n- **Worm-like propagation** if the payload can create additional stored XSS entries\n- **Administrative account compromise** if admins view user-generated content\n- **Data exfiltration** from the application on behalf of any affected user\n- **Full account takeover** of any user who views the injected content',
  'markdown',
  E'1. **Sanitize and encode all user input** before storage and before rendering — apply context-appropriate output encoding\n2. **Implement a strict Content Security Policy** that prevents inline script execution\n3. **Use a proven HTML sanitization library** (e.g., DOMPurify) for any rich text or user-generated content\n4. **Validate input** on the server side with strict allow-lists\n5. **Review all locations** where user-generated content is rendered for proper encoding',
  'markdown',
  'high',
  8.1,
  'CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:H/I:L/A:N',
  true
),
(
  'Insecure Direct Object Reference (IDOR)',
  'web',
  E'The application exposes internal object references (such as database IDs, filenames, or sequential identifiers) in API endpoints or URLs and fails to verify that the authenticated user is authorized to access the referenced object. By manipulating these references, an attacker can access or modify resources belonging to other users.\n\nDuring testing, it was confirmed that modifying the object identifier in requests allowed access to another user''s data without any authorization check beyond authentication.',
  'markdown',
  E'An attacker could:\n\n- **Access sensitive data** belonging to other users (personal information, documents, financial records)\n- **Modify or delete** other users'' resources\n- **Escalate privileges** by accessing administrative objects\n- **Enumerate all records** in the system by iterating through sequential IDs',
  'markdown',
  E'1. **Implement server-side authorization checks** on every request — verify the authenticated user has permission to access the specific resource\n2. **Use indirect references** such as UUIDs or per-session mapping tables instead of sequential database IDs\n3. **Apply the principle of least privilege** in access control logic\n4. **Log and monitor** access patterns for anomalous enumeration attempts\n5. **Conduct authorization testing** across all API endpoints and user roles',
  'markdown',
  'high',
  7.5,
  'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N',
  true
),
(
  'Server-Side Request Forgery (SSRF)',
  'web',
  E'A server-side request forgery vulnerability was identified. The application accepts user-supplied URLs or hostnames and makes server-side HTTP requests to those destinations without adequate validation. An attacker can abuse this to make the server send requests to internal services, cloud metadata endpoints, or other restricted resources.\n\nThis was demonstrated by supplying internal IP addresses and cloud metadata URLs, which returned sensitive internal data.',
  'markdown',
  E'An attacker exploiting SSRF could:\n\n- **Access cloud metadata services** (e.g., AWS IMDSv1 at 169.254.169.254) to steal IAM credentials\n- **Port scan and fingerprint** internal network services\n- **Access internal APIs** and administration interfaces not exposed to the internet\n- **Read local files** via `file://` protocol handlers (depending on implementation)\n- **Pivot to internal systems** to chain with other vulnerabilities',
  'markdown',
  E'1. **Validate and restrict** user-supplied URLs to an allow-list of approved domains and protocols\n2. **Block requests** to private/reserved IP ranges (10.x, 172.16-31.x, 192.168.x, 169.254.x, 127.x)\n3. **Use cloud provider protections** such as AWS IMDSv2 (requiring session tokens)\n4. **Disable unnecessary URL schemes** (block file://, gopher://, dict://, etc.)\n5. **Implement network-level controls** to prevent the application server from reaching sensitive internal services',
  'markdown',
  'high',
  7.5,
  'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N',
  true
),
(
  'Weak / Default Credentials',
  'general',
  E'One or more systems or services were found using default, weak, or easily guessable credentials. These include vendor default username/password combinations, common passwords (e.g., "admin/admin", "password", "123456"), or credentials derivable from publicly available documentation.\n\nWeak credentials represent one of the most common initial access vectors in real-world attacks and are trivially exploitable with automated tools.',
  'markdown',
  E'Exploitation could result in:\n\n- **Unauthorized access** to administrative interfaces, databases, or infrastructure\n- **Full system compromise** if the compromised account has elevated privileges\n- **Lateral movement** using the compromised credentials on other systems (credential reuse)\n- **Data breach** if the compromised account has access to sensitive information',
  'markdown',
  E'1. **Change all default credentials** immediately upon deployment of any system or service\n2. **Enforce a strong password policy** — minimum 12 characters, complexity requirements, and prohibition of common passwords\n3. **Implement multi-factor authentication (MFA)** on all administrative and remote access interfaces\n4. **Deploy account lockout policies** to mitigate brute-force attacks\n5. **Conduct regular credential audits** and integrate password strength checking against known breach databases (e.g., HaveIBeenPwned)',
  'markdown',
  'high',
  7.5,
  'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N',
  true
),
(
  'Missing Rate Limiting',
  'api',
  E'The application does not implement rate limiting on sensitive endpoints such as authentication, password reset, or API data retrieval. An attacker can make unlimited requests without being throttled or blocked, enabling brute-force attacks, credential stuffing, and enumeration.\n\nDuring testing, thousands of requests were submitted to the login endpoint without any rate limiting, lockout, or CAPTCHA mechanism being triggered.',
  'markdown',
  E'Without rate limiting, an attacker could:\n\n- **Brute-force credentials** against the login endpoint\n- **Enumerate valid usernames** via differing response times or messages\n- **Perform credential stuffing** using leaked credential databases\n- **Abuse resource-intensive operations** to cause denial of service\n- **Harvest data** through mass API enumeration',
  'markdown',
  E'1. **Implement rate limiting** on all authentication endpoints — recommend maximum 5 attempts per minute with progressive backoff\n2. **Add rate limits** to all API endpoints based on business requirements\n3. **Deploy CAPTCHA** or proof-of-work challenges after repeated failed attempts\n4. **Implement account lockout** with time-based recovery for excessive failed login attempts\n5. **Monitor and alert** on anomalous request volumes',
  'markdown',
  'medium',
  5.3,
  'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N',
  true
),
(
  'LLMNR/NBT-NS Poisoning',
  'network',
  E'Link-Local Multicast Name Resolution (LLMNR) and NetBIOS Name Service (NBT-NS) are enabled on the network and responding to broadcast name resolution queries. These legacy protocols allow any host on the local network to respond to name resolution requests, enabling an attacker to capture NTLMv2 hashes by poisoning responses and redirecting authentication to a rogue server.\n\nUsing Responder, NTLMv2 challenge-response hashes were captured from multiple hosts on the network. Several of these hashes were subsequently cracked offline, yielding plaintext domain credentials.',
  'markdown',
  E'Exploitation allows an attacker to:\n\n- **Capture NTLMv2 hashes** of domain users passively on the network\n- **Crack hashes offline** to obtain plaintext credentials (no account lockout triggered)\n- **Relay authentication** to other services via NTLM relay attacks (e.g., to LDAP, SMB, HTTP)\n- **Gain initial foothold** in the Active Directory environment\n- **Move laterally** using compromised credentials',
  'markdown',
  E'1. **Disable LLMNR** via Group Policy: Computer Configuration → Administrative Templates → Network → DNS Client → Turn Off Multicast Name Resolution = Enabled\n2. **Disable NBT-NS** via DHCP options or network adapter settings\n3. **Enable SMB signing** on all systems to prevent NTLM relay attacks\n4. **Enable EPA (Extended Protection for Authentication)** on LDAP and web services\n5. **Deploy network segmentation** to limit broadcast domains and lateral movement potential',
  'markdown',
  'high',
  7.5,
  'CVSS:3.1/AV:A/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N',
  true
),
(
  'Kerberoasting',
  'active_directory',
  E'Service accounts in the Active Directory environment are configured with Service Principal Names (SPNs) and use weak or brute-forceable passwords. Any authenticated domain user can request Kerberos service tickets (TGS) for these accounts, extract the tickets, and attempt offline password cracking — a technique known as Kerberoasting.\n\nDuring testing, TGS tickets were requested for all SPN-enabled accounts and several service account passwords were cracked within minutes using hashcat with a standard wordlist.',
  'markdown',
  E'Successful Kerberoasting allows an attacker to:\n\n- **Compromise service accounts** that often have elevated privileges or domain admin access\n- **Gain persistence** through service account credentials that rarely change\n- **Access sensitive systems** that the service account is authorized for (databases, file shares, applications)\n- **Escalate to Domain Admin** if any Kerberoastable account has DA-equivalent privileges',
  'markdown',
  E'1. **Use Group Managed Service Accounts (gMSAs)** where possible — these have automatically rotated 120-character passwords that are immune to Kerberoasting\n2. **Set strong passwords (25+ characters)** on all accounts with SPNs registered\n3. **Implement a regular audit** of accounts with SPNs: `Get-ADUser -Filter {ServicePrincipalName -ne "$null"}`\n4. **Remove unnecessary SPNs** from accounts that no longer require them\n5. **Enable AES encryption** for Kerberos tickets and disable RC4-HMAC to make cracking harder\n6. **Monitor for TGS requests** with anomalous patterns using security event ID 4769',
  'markdown',
  'high',
  7.5,
  'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N',
  true
),
(
  'AS-REP Roasting',
  'active_directory',
  E'One or more Active Directory accounts are configured with "Do not require Kerberos preauthentication" enabled. This allows any user (or even an unauthenticated attacker with a list of usernames) to request an AS-REP (Authentication Service Response) for these accounts and attempt offline password cracking — a technique known as AS-REP Roasting.\n\nDuring testing, AS-REP hashes were obtained for accounts with preauthentication disabled and passwords were subsequently cracked offline.',
  'markdown',
  E'An attacker could:\n\n- **Crack account passwords offline** without triggering account lockout\n- **Gain unauthorized access** to the compromised accounts and their resources\n- **Escalate privileges** if any affected account has elevated permissions\n- **Perform this attack unauthenticated** if valid usernames can be enumerated',
  'markdown',
  E'1. **Enable Kerberos preauthentication** on all accounts — audit with: `Get-ADUser -Filter {DoesNotRequirePreAuth -eq $true}`\n2. **Enforce strong passwords** on any accounts that must have preauthentication disabled (rare legacy requirement)\n3. **Monitor for AS-REP requests** using security event ID 4768 with pre-authentication type 0\n4. **Remove the "Do not require Kerberos preauthentication" flag** from all accounts where it is not strictly required',
  'markdown',
  'medium',
  6.5,
  'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N',
  true
),
(
  'Unrestricted File Upload',
  'web',
  E'The application allows users to upload files without adequate validation of file type, content, or size. An attacker can upload malicious files such as web shells, server-side scripts, or specially crafted payloads that execute on the server when accessed.\n\nDuring testing, a web shell was successfully uploaded by bypassing the client-side file type restriction, which only checked the file extension. The server did not validate the file''s content or MIME type.',
  'markdown',
  E'An attacker could:\n\n- **Achieve remote code execution** by uploading and executing a web shell\n- **Compromise the server** and access all data and internal network resources\n- **Establish persistent access** through uploaded backdoors\n- **Serve malware** to other users through uploaded files\n- **Deny service** by uploading excessively large files',
  'markdown',
  E'1. **Validate file type on the server** by checking both the MIME type and file content (magic bytes), not just the extension\n2. **Restrict uploaded file types** to a strict allow-list of required formats\n3. **Store uploaded files outside the web root** and serve them through a separate handler that sets Content-Disposition: attachment\n4. **Rename uploaded files** to random names to prevent direct execution\n5. **Scan uploaded files** with antivirus/anti-malware before storage\n6. **Enforce file size limits** appropriate to the application''s requirements',
  'markdown',
  'high',
  8.8,
  'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H',
  true
),
(
  'Cross-Site Request Forgery (CSRF)',
  'web',
  E'The application does not implement anti-CSRF tokens or other CSRF protection mechanisms on state-changing requests. An attacker can craft a malicious webpage that, when visited by an authenticated user, silently submits requests to the application on the user''s behalf.\n\nDuring testing, a proof-of-concept HTML page was created that successfully performed state-changing actions (such as changing account settings) when visited by an authenticated user in a separate browser tab.',
  'markdown',
  E'An attacker could force authenticated users to:\n\n- **Change account settings** including email address and password\n- **Make financial transactions** or approve requests\n- **Modify data** or delete resources\n- **Add attacker-controlled administrators** to the application',
  'markdown',
  E'1. **Implement anti-CSRF tokens** (synchronizer token pattern) on all state-changing forms and AJAX requests\n2. **Use the SameSite cookie attribute** (Lax or Strict) on session cookies\n3. **Verify the Origin and Referer headers** on state-changing requests\n4. **Require re-authentication** for sensitive operations (password change, email change)\n5. **Use framework-provided CSRF protection** mechanisms (e.g., Next.js server actions include CSRF protection by default)',
  'markdown',
  'medium',
  6.5,
  'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N',
  true
),
(
  'Publicly Accessible Cloud Storage',
  'cloud',
  E'One or more cloud storage resources (e.g., AWS S3 buckets, Azure Blob containers, GCP Storage buckets) were found to be publicly accessible. Unauthenticated users can list and download objects from the storage resource, potentially exposing sensitive data including customer information, application secrets, backups, and internal documents.\n\nThe publicly accessible storage resources were identified through enumeration and confirmed by successfully listing and downloading objects without authentication.',
  'markdown',
  E'Publicly accessible cloud storage could lead to:\n\n- **Data breach** — exposure of customer PII, financial data, or protected health information\n- **Credential exposure** — access to configuration files containing API keys, database credentials, or secrets\n- **Intellectual property theft** — exposure of source code, internal documentation, or proprietary data\n- **Regulatory violations** — GDPR, HIPAA, PCI-DSS compliance failures\n- **Reputational damage** from publicly disclosed data exposure',
  'markdown',
  E'1. **Immediately restrict public access** to all cloud storage resources — enable "Block Public Access" settings\n2. **Audit all storage resources** for public access using cloud provider tools (AWS Access Analyzer, Azure Policy, GCP IAM Analyzer)\n3. **Implement cloud security posture management (CSPM)** to continuously monitor for misconfigurations\n4. **Apply the principle of least privilege** to storage IAM policies\n5. **Enable access logging** on all storage resources to detect unauthorized access\n6. **Encrypt data at rest** and use server-side encryption with customer-managed keys',
  'markdown',
  'high',
  7.5,
  'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N',
  true
),
(
  'Outdated Software with Known Vulnerabilities',
  'general',
  E'One or more systems or services are running outdated software versions with known, publicly disclosed vulnerabilities (CVEs). These vulnerabilities have published exploit code and are actively targeted by attackers. The affected software includes [software name/version] which is vulnerable to [CVE-XXXX-XXXXX].\n\nThe outdated versions were identified through banner analysis, HTTP response headers, and version fingerprinting during testing.',
  'markdown',
  E'Running unpatched software exposes the environment to:\n\n- **Exploitation using public exploit code** that requires minimal attacker skill\n- **Remote code execution** depending on the specific vulnerability\n- **Data exposure** through known information disclosure flaws\n- **Denial of service** from crash-inducing vulnerabilities\n- **Automated mass exploitation** by botnets scanning for known vulnerable versions',
  'markdown',
  E'1. **Patch immediately** — update all affected software to the latest stable versions\n2. **Implement a vulnerability management program** with regular scanning and defined SLAs for patching (critical: 24-72 hours, high: 1-2 weeks)\n3. **Enable automatic updates** where appropriate, particularly for operating systems and web browsers\n4. **Subscribe to vendor security advisories** and CVE feeds for all deployed software\n5. **Maintain a software inventory** to track versions across the environment\n6. **Apply virtual patching** via WAF or IPS rules as an interim measure while patching is scheduled',
  'markdown',
  'high',
  7.5,
  'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N',
  true
),
(
  'Missing Security Headers',
  'web',
  E'The application is missing one or more recommended HTTP security headers that provide defense-in-depth against common web attacks. While missing headers alone do not constitute a direct exploitable vulnerability, they remove important security controls that mitigate the impact of other vulnerabilities such as XSS, clickjacking, and MIME-type confusion attacks.\n\nThe following headers were found to be missing or misconfigured:\n- Content-Security-Policy (CSP)\n- X-Content-Type-Options\n- X-Frame-Options / frame-ancestors\n- Strict-Transport-Security (HSTS)\n- Referrer-Policy\n- Permissions-Policy',
  'markdown',
  E'Missing security headers increase exposure to:\n\n- **Cross-site scripting (XSS)** — without CSP, injected scripts execute without restriction\n- **Clickjacking** — without X-Frame-Options, the application can be framed by malicious sites\n- **MIME-type sniffing** — without X-Content-Type-Options, browsers may interpret files as executable\n- **Downgrade attacks** — without HSTS, connections may be intercepted via HTTP\n- **Information leakage** — without Referrer-Policy, sensitive URL parameters may leak to third parties',
  'markdown',
  E'Add the following headers to all HTTP responses:\n\n1. **Content-Security-Policy**: `default-src ''self''; script-src ''self''; style-src ''self'' ''unsafe-inline''` (customize per application needs)\n2. **X-Content-Type-Options**: `nosniff`\n3. **X-Frame-Options**: `DENY` (or use CSP frame-ancestors)\n4. **Strict-Transport-Security**: `max-age=31536000; includeSubDomains; preload`\n5. **Referrer-Policy**: `strict-origin-when-cross-origin`\n6. **Permissions-Policy**: Restrict browser features not required by the application',
  'markdown',
  'low',
  3.7,
  'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N',
  true
);
